niveau0: main.c GENERAL/sdl-light.c GENERAL/sdl-light.h GAME/init_combat.c GAME/init_combat.h GAME/combat.c GAME/combat.h GAME/ATTAQUE/SNAKE/init_snake.c GAME/ATTAQUE/SNAKE/init_snake.h GAME/ATTAQUE/SNAKE/snake.c GAME/ATTAQUE/SNAKE/init_snake.h GAME/ATTAQUE/DEVINE_COULEUR/init_devine_couleur.c GAME/ATTAQUE/DEVINE_COULEUR/init_devine_couleur.h GAME/ATTAQUE/DEVINE_COULEUR/devine_couleur.c GAME/ATTAQUE/DEVINE_COULEUR/devine_couleur.h GAME/FUIR/fuir.c GAME/FUIR/fuir.h GAME/FUIR/init_fuir.c GAME/FUIR/init_fuir.h GAME/EPARGNER/epargner.c GAME/EPARGNER/epargner.h GAME/EPARGNER/init_epargner.c GAME/EPARGNER/init_epargner.h MENU/MENU_IN_GAME/menu.c MENU/MENU_IN_GAME/menu.h MENU/MENU_IN_GAME/init_menu.c MENU/MENU_IN_GAME/init_menu.h  MENU/MENU_DEMARRER/menu_demarrer.c MENU/MENU_DEMARRER/menu_demarrer.h MENU/MENU_DEMARRER/init_menu_demarrer.c MENU/MENU_DEMARRER/init_menu_demarrer.c UPDATE/update.c UPDATE/update.h INIT/init.c INIT/init.h GENERAL/general.h 
	clear
	clear
	gcc -Wall -g  -std=c99 main.c GENERAL/sdl-light.c GAME/init_combat.c GAME/combat.c GAME/ATTAQUE/SNAKE/snake.c GAME/ATTAQUE/SNAKE/init_snake.c GAME/ATTAQUE/DEVINE_COULEUR/init_devine_couleur.c GAME/ATTAQUE/DEVINE_COULEUR/devine_couleur.c GAME/FUIR/fuir.c GAME/FUIR/init_fuir.c GAME/EPARGNER/epargner.c GAME/EPARGNER/init_epargner.c MENU/MENU_IN_GAME/menu.c  MENU/MENU_IN_GAME/init_menu.c MENU/MENU_DEMARRER/menu_demarrer.c MENU/MENU_DEMARRER/init_menu_demarrer.c UPDATE/update.c INIT/init.c -lm `sdl-config --cflags --libs` -o niveau0

clean:
	rm -f niveau0

	
