niveau0: main.c GENERAL/sdl-light.c GENERAL/sdl-light.h UPDATE/update.c UPDATE/update.h INIT/init.c INIT/init.h GENERAL/general.h
	clear
	clear
	gcc -Wall -g  -std=c99 main.c GENERAL/sdl-light.c UPDATE/update.c INIT/init.c -lm `sdl-config --cflags --libs` -o niveau0

clean:
	rm -f niveau0
